jobs:
- job: BuildMac
  displayName: Build MacOS, Windows and Android
  pool:
    vmImage: xcode9-macos10.13
  steps:
  - script: |
      brew tap xamarin/xamarin-android-windeps
      brew upgrade https://raw.githubusercontent.com/Homebrew/homebrew-core/a6542037a48a55061a4c319e6bb174b3715f7cbe/Formula/mingw-w64.rb
      brew install mingw-w64
      brew install ninja xamarin/xamarin-android-windeps/mingw-zlib p7zip
    displayName: 'Install Tools'
  - bash: |
      git submodule update --init --recursive
    displayName: 'Update Submodules'
  - bash: |
      ./build_native
    displayName: 'Build Darwin'
  - bash: |
      ./build_windows
    displayName: 'Build Windows'
  - bash: |
      ./build_android
    displayName: 'Build Android'
    env:
      OUTPUT: $(Build.ArtifactStagingDirectory)
  - task: ArchiveFiles@2
    displayName: 'Archive MacOS'
    inputs:
      rootFolderOrFile: build/Darwin/vcdiff
      includeRootFolder: false 
      archiveType: 7z
      archiveFile: $(Build.ArtifactStagingDirectory)/vcdiff-0.8.4-macos.7z
  - task: ArchiveFiles@2
    displayName: 'Archive Windows'
    inputs:
      rootFolderOrFile: build/Windows/64/vcdiff.exe
      includeRootFolder: false 
      archiveType: 7z
      archiveFile: $(Build.ArtifactStagingDirectory)/vcdiff-0.8.4-windows.7z
  - task: PublishBuildArtifacts@1
    displayName: upload artifacts
    inputs:
      artifactName: vcdiff
      pathtoPublish: $(Build.ArtifactStagingDirectory)
- job: BuildLinux
  displayName: Build Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: |
      sudo apt -y update
      sudo apt install ninja-build -y
    displayName: 'Install Tools'
  - bash: |
      git submodule update --init --recursive
    displayName: 'Update Submodules'
  - bash: |
      ./build_native
    displayName: 'Build Linux'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: build/Linux/vcdiff
      includeRootFolder: false 
      archiveType: 7z
      archiveFile: $(Build.ArtifactStagingDirectory)/vcdiff-0.8.4-linux.7z
  - task: PublishBuildArtifacts@1
    displayName: upload artifacts
    inputs:
      artifactName: vcdiff
      pathtoPublish: $(Build.ArtifactStagingDirectory)
- job: BuildNuget
  displayName: 'Build Nuget'
  dependsOn:
  - BuildMac
  - BuildLinux
  pool:
    vmImage: xcode9-macos10.13
  steps:
    - task: DownloadBuildArtifacts@0
      displayName: download artifacts
      inputs:
        artifactName: vcdiff
        downloadPath: $(Build.ArtifactStagingDirectory)
    - task: ExtractFiles@1
      displayName: Extract Darwin Artifacts
      inputs:
        archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/vcdiff/vcdiff-*-macos.7z'
        destinationFolder: build/Darwin
    - task: ExtractFiles@1
      displayName: Extract Windows Artifacts
      inputs:
        archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/vcdiff/vcdiff-*-windows.7z'
        destinationFolder: build/Windows/64
    - task: ExtractFiles@1
      displayName: Extract Linux Artifacts
      inputs:
        archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/vcdiff/vcdiff-*-linux.7z'
        destinationFolder: build/Linux
    - task: ExtractFiles@1
      displayName: Extract Android Artifacts
      inputs:
        archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/vcdiff/vcdiff-*-android.7z'
        destinationFolder: build/Android
    - task: NuGetCommand@2
      displayName: package nuget
      inputs:
        command: custom
        arguments: pack vcdiff.nuspec
        packDestination: '$(Build.ArtifactStagingDirectory)'

